### ISSUE TITLE
App crashes every time I make a task or uncheck a completed task

### ISSUE THREAD

**Issue by eddieofny** [darkmoonight/ToDark#56]
Anytime I finish creating a task, or if I unchecked a completed task, the app will crash. I don't know java, but both crashes look very similar in logfox. I'll post both logs below.

 - Device: LG K20 Plus
 - OS: Android 7.0
 - App Version 1.4.9

**Additional context**
I'm not sure if it's relevant or not, but I installed the app via Obtainium since I needed the V7a version.

LOG 1 (from when I created a new task):

FATAL EXCEPTION: main
Process: com.yoshi.todark, PID: 30914
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDateTime;
	at com.dexterous.flutterlocalnotifications.m0.a(SourceFile)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(SourceFile)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(SourceFile)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(SourceFile)
	at g3.k$a.a(SourceFile)
	at u2.c.l(SourceFile)
	at u2.c.m(SourceFile)
	at u2.c.i(SourceFile)
	at u2.b.run(SourceFile)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6316)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.LocalDateTime" on path: DexPathList[[zip file "/data/app/com.yoshi.todark-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yoshi.todark-1/lib/arm, /data/app/com.yoshi.todark-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 17 more

LOG 2 (from when I unchecked a completed task):

FATAL EXCEPTION: main
Process: com.yoshi.todark, PID: 31078
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDateTime;
	at com.dexterous.flutterlocalnotifications.m0.a(SourceFile)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(SourceFile)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(SourceFile)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(SourceFile)
	at g3.k$a.a(SourceFile)
	at u2.c.l(SourceFile)
	at u2.c.m(SourceFile)
	at u2.c.i(SourceFile)
	at u2.b.run(SourceFile)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6316)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.LocalDateTime" on path: DexPathList[[zip file "/data/app/com.yoshi.todark-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yoshi.todark-1/lib/arm, /data/app/com.yoshi.todark-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 17 more

**Comment by Leonavichus** [comment]
Can you see if everything is working fine now?
